-- Drop the database if it exists
DROP DATABASE IF EXISTS Bank;

-- Create the Bank database
CREATE DATABASE Bank;

-- Switch to the Bank database
USE Bank;

-- CUSTOMER_PERSONAL_INFO

CREATE TABLE CUSTOMER_PERSONAL_INFO (
    CUSTOMER_ID VARCHAR(5),
    CUSTOMER_NAME VARCHAR(30),
    DATE_OF_BIRTH DATE,
    GUARDIAN_NAME VARCHAR(30),
    ADDRESS VARCHAR(50),
    CONTACT_NO VARCHAR(20), 
    MAIL_ID VARCHAR(30),
    GENDER CHAR(1),
    MARITAL_STATUS VARCHAR(10),
    IDENTIFICATION_DOC_TYPE VARCHAR(20),
    ID_DOC_NO VARCHAR(20),
    CITIZENSHIP VARCHAR(10),
    CONSTRAINT CUST_PERS_INFO_PK PRIMARY KEY (CUSTOMER_ID)
);

-- CUSTOMER_REFERENCE_INFO

CREATE TABLE CUSTOMER_REFERENCE_INFO (
    CUSTOMER_ID VARCHAR(5),
    REFERENCE_ACC_NAME VARCHAR(30),
    REFERENCE_ACC_NO BIGINT(16),
    REFERENCE_ACC_ADDRESS VARCHAR(50),
    RELATION VARCHAR(25),
    CONSTRAINT CUST_REF_INFO_PK PRIMARY KEY (CUSTOMER_ID),
    CONSTRAINT CUST_REF_INFO_FK FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER_PERSONAL_INFO(CUSTOMER_ID)
);

-- BANK_INFO

CREATE TABLE BANK_INFO (
    IFSC_CODE VARCHAR(15),
    BANK_NAME VARCHAR(25),
    BRANCH_NAME VARCHAR(25),
    CONSTRAINT BANK_INFO_PK PRIMARY KEY(IFSC_CODE)
);

-- ACCOUNT_INFO

CREATE TABLE ACCOUNT_INFO (
    ACCOUNT_NO BIGINT(16),
    CUSTOMER_ID VARCHAR(5),
    ACCOUNT_TYPE VARCHAR(10),
    REGISTRATION_DATE DATE,
    ACTIVATION_DATE DATE,
    IFSC_CODE VARCHAR(15),
    INTEREST DECIMAL(7,2),
    INITIAL_DEPOSIT BIGINT(10),
    CONSTRAINT ACC_INFO_PK PRIMARY KEY (ACCOUNT_NO),
    CONSTRAINT ACC_INFO_PERKS_FK FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER_PERSONAL_INFO(CUSTOMER_ID),
    CONSTRAINT ACC_INFO_BANK_FK FOREIGN KEY (IFSC_CODE) REFERENCES BANK_INFO(IFSC_CODE)
);

-- Insert data into BANK_INFO


INSERT INTO BANK_INFO(IFSC_CODE, BANK_NAME, BRANCH_NAME) VALUES('HDVL001', 'SBI', 'GORE');
INSERT INTO BANK_INFO(IFSC_CODE, BANK_NAME, BRANCH_NAME) VALUES('SDLV002', 'HDFC', 'ORE');
INSERT INTO BANK_INFO(IFSC_CODE, BANK_NAME, BRANCH_NAME) VALUES('ICIT003', 'KOTAK', 'NON');
INSERT INTO BANK_INFO(IFSC_CODE, BANK_NAME, BRANCH_NAME) VALUES('SBIN004', 'INDIAN', 'PON');
INSERT INTO BANK_INFO(IFSC_CODE, BANK_NAME, BRANCH_NAME) VALUES('ICIN005', 'BARODA', 'WON');

-- Select data from BANK_INFO

SELECT * FROM BANK_INFO;

-- CUSTOMER_PERSONAL_INFO

INSERT INTO CUSTOMER_PERSONAL_INFO (CUSTOMER_ID, CUSTOMER_NAME, DATE_OF_BIRTH, CONTACT_NO) VALUES('1', 'ABD', '2000-11-29', '1234567890');
INSERT INTO CUSTOMER_PERSONAL_INFO (CUSTOMER_ID, CUSTOMER_NAME, DATE_OF_BIRTH, CONTACT_NO) VALUES('2', 'nihal', '2001-02-28', '9876543210');
INSERT INTO CUSTOMER_PERSONAL_INFO (CUSTOMER_ID, CUSTOMER_NAME, DATE_OF_BIRTH, CONTACT_NO) VALUES('3', 'bavitha', '2002-06-05', '5555555555');
INSERT INTO CUSTOMER_PERSONAL_INFO (CUSTOMER_ID, CUSTOMER_NAME, DATE_OF_BIRTH, CONTACT_NO) VALUES('4', 'kasim', '2003-04-09', '1231231234');
INSERT INTO CUSTOMER_PERSONAL_INFO (CUSTOMER_ID, CUSTOMER_NAME, DATE_OF_BIRTH, CONTACT_NO) VALUES('5', 'mohamed', '2004-06-10', '4567890123');


SELECT * FROM CUSTOMER_PERSONAL_INFO;
